[package]
name = "bcrypt-utils"
version = "1.0.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bcrypt = "0.10"

[profile.release]
opt-level = 3